### ISSUE TITLE
cache brushes

### ISSUE THREAD

**Issue by cztomsik** [cztomsik/node-webrender#46]
this is react-specific, ResourceManager shouldn't deal with this but any call to `ResourceManager.getBrush(StyleSheet.flatten(...))` should be optimized

we should somehow detect static styles and come up with caching intermediate results (at least if all of styles are static)

it also means we should mark styles as static in StyleSheet.create() somehow.

related to #39

**Comment by twop** [comment]
AFAIK RN caches all calls to StyleSheet.create(). Essentially it gives back a handle.

**Comment by cztomsik** [comment]
it's not true anymore
facebook/react-native@a8e3c7f

they were not using it but we will so it makes sense to do something like that

**Comment by cztomsik** [comment]
WIP, but mostly done (we have to find sources of anonymous buckets + implement some sort of gc)

I think it could work in a probabillistic fashion, I'm not sure how to call this but it's not classic LRUCache, it should do fast lookups and sometimes check if it's not over capacity and if it is, it should randomly drop first N items and increase capacity a bit. This way it should be fast & it should not leak much in practice
